version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883" # Per il backend Java
      - "9001:9001" # Per il frontend React (WebSocket)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - my-net


volumes:
  mosquitto_data:
  mosquitto_log:


networks:
  my-net:
    driver: bridge