persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Ascolta su TCP standard (per Java Backend)
listener 1883
allow_anonymous true

# Ascolta su WebSockets (per React Frontend)
listener 9001
protocol websockets
allow_anonymous true

